Add https example
Signed-off-by: csh <458761603@qq.com>

diff --git a/.github/workflows/examples.yml b/.github/workflows/examples.yml
--- a/.github/workflows/examples.yml
+++ b/.github/workflows/examples.yml
@@ -35,12 +35,27 @@ jobs:
       run: |
         VERSION=0.13.5
         curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | sudo bash -s -- --version=$VERSION -p /usr/local
-    
+        
+        sudo mkdir -p /usr/local/lib/wasmedge
+        wget https://github.com/WasmEdge/WasmEdge/releases/download/$VERSION/WasmEdge-plugin-wasmedge_rustls-$VERSION-ubuntu20.04_x86_64.tar.gz
+        tar -zxf WasmEdge-plugin-wasmedge_rustls-$VERSION-ubuntu20.04_x86_64.tar.gz
+        sudo mv libwasmedge_rustls.so /usr/local/lib/wasmedge
+
     - name: Client example
       run: |
         cargo build --target wasm32-wasi --release
-        wasmedgec target/wasm32-wasi/release/wasmedge_reqwest_demo.wasm wasmedge_reqwest_demo.wasm
-        resp=$(wasmedge wasmedge_reqwest_demo.wasm 2>&1)
+        wasmedgec target/wasm32-wasi/release/http.wasm http.wasm
+        wasmedgec target/wasm32-wasi/release/https.wasm https.wasm
+        resp=$(wasmedge http.wasm 2>&1)
+        echo "$resp"
+        if [[ $resp == *"WasmEdge"* ]]; then
+          echo -e "Execution Success!"
+        else
+          echo -e "Execution Fail!"
+          exit 1
+        fi
+
+        resp=$(wasmedge https.wasm 2>&1)
         echo "$resp"
         if [[ $resp == *"WasmEdge"* ]]; then
           echo -e "Execution Success!"
